### ISSUE TITLE
make vega-lite render arbitrary chart in SOCRAT

### ISSUE THREAD

**Issue by alxndrkalinin** [SOCR/SOCRAT-issues#104]
Just take a simple vega-lite [chart config](https://vega.github.io/vega-lite/), hard code it into charts, and using vega-lite and vega render it in the MainArea of Charts module.

Take a look at the [vega-lite-ui](https://github.com/vega/vega-lite-ui) package that provides AngulaJs-based UI for vega-lite apps.

**Comment by acell** [comment]
ok.... kinda did somethn.....
<img width="992" alt="screen shot 2017-02-16 at 3 34 02 pm" src="https://cloud.githubusercontent.com/assets/17788969/23039960/84a67124-f45d-11e6-910a-430ed7de32d0.png">
