### ISSUE TITLE
figure out how to combine different mini-plots

### ISSUE THREAD

**Issue by alxndrkalinin** [SOCR/SOCRAT-issues#140]
Need to figure out if it's possible to combine different kinds of plots in one trellis plot using vega-lite, i.e. all [scatterplots](https://vega.github.io/vega-editor/?mode=vega-lite&spec=trellis_scatter) except for histograms on a diagonal (see #105 for an example).

**Comment by acell** [comment]
http://vega.github.io/vega-editor/?mode=vega&spec=linking
I haven't seen any examples of this / can't conceptualize how it would work using vega-lite (and definitely not without being overly hacky). This is the alternative that seems to be recommended. At some point when I'm more familiar with vega-lite I might be able to think of something ??? But for now this seems OK.
<img width="615" alt="screen shot 2017-02-16 at 3 20 10 am" src="https://cloud.githubusercontent.com/assets/17788969/23013172/94829976-f3f7-11e6-9573-ec829c813911.png">

**Comment by alxndrkalinin** [comment]
@acell have you seen [vega-lite doc](https://vega.github.io/vega-lite/docs/facet.html) on trellis plots? Looks like there might be a mechanism to do it.
I spent 3 min in the editor and was able to get this:
![vega](https://cloud.githubusercontent.com/assets/1107762/23040302/d64be2f6-f45e-11e6-8e99-1891774c3143.png)
Maybe worth exploring further. See the config:
```
{
  "data": {"url": "data/iris.json"},
  "mark": "bar",
  "encoding": {
    "x": {
      "bin": {"maxbins": 5},
      "field": "petalWidth",
      "type": "quantitative"
    },
    "y": {
      "bin": {"maxbins": 5},
      "field": "sepalLength",
      "type": "quantitative"
    },
    "row": {"field": "petalLength","type": "nominal","bin": {"maxbins": 5}},
    "column": {"field": "sepalWidth","type": "nominal","bin": {"maxbins": 5}}
  }
}
```
If this doesn't work out we can try vega itself, it should have more low-level controls.
