### ISSUE TITLE
create compiling instructions for wrangler

### ISSUE THREAD

**Issue by fengyuz** [SOCR/SOCRAT-issues#147]

**Comment by hck94829** [comment]
Need a Java environment to work with:
1. Download the Closure Compiler package to the working directory (closure-compiler-v20170124.jar was my version, change the name if needed)
2. Run 'java -jar closure-compiler-v20170124.jar --js file_to_be_compiled.js --js_output_file out.js' in the current directory
3. This should give the compiled file in 'out.js'
4. If need prettified format, add '--formatting PRETTY_PRINT'

**Comment by alxndrkalinin** [comment]
elaborated in #168
