### ISSUE TITLE
fix WorldBank API

### ISSUE THREAD

**Issue by alxndrkalinin** [SOCR/SOCRAT-issues#150]
We need to fix WordBank API and add few more options for dataset. So far I was using 20.000 cells as a soft limit for dataset size to allow clustering/bootstrapping – so number of record to retrieve can be calculated as 20.000/#cols. However, user can get more records and then SOCRAT will suggest to uniformly subsample rows.

Subtasks:
- [x] fix Education spending
- [x] fix Out-of-school children rate
- [ ] add few more datasets (up to 10-15)
- [x] fix styling of controls: inputs, dropdowns (we're using [FlatUI](https://designmodo.github.io/Flat-UI/docs/components.html))

**Comment by chartotu19** [comment]
@alxndrkalinin So if the user imports more than 2000/column, app should limit the number of rows to satisfy - `rows*columns == 2000`. Did I get that right? 
Also, Is there any mathematical technique for sub sampling or just `Math.random`?

**Comment by alxndrkalinin** [comment]
@chartotu19, sorry, typo, it's 20.000

I was talking about 20.000/#cols as a way to figure out what would be a default value for how many rows by default to request from WorldBank. E.g. if Education Spending category has 10 columns, than you show 2.000 rows as a default. However it's okay to let user to request more (up to max allowed by API).

Also, subsampling is already implemented – e.g., if you try loading Knee Pain dataset it'll suggest subsampling

![screen shot 2017-03-07 at 10 01 17 pm](https://cloud.githubusercontent.com/assets/1107762/23688292/a9f4008a-0381-11e7-9a51-a9fc158a0586.png)

**Comment by chartotu19** [comment]
the fix for missing header is pushed now. PR is ready to be merged feature-wise
