### ISSUE TITLE
Unable to upload raw data on local server after new cloning of SOCRAT repo

### ISSUE THREAD

**Issue by acell** [SOCR/SOCRAT-issues#2]
* as depicted in the screenshot, there is no option to upload a file to use as data or to use datasets provided by the toolbar on my local server
* cites that a transition was superseded, prevented, aborted, and then failed
* this issue does not exist on the production app

<img width="893" alt="screen shot 2017-01-22 at 5 07 53 pm" src="https://cloud.githubusercontent.com/assets/17788969/22186537/6ee46162-e0c5-11e6-9751-a2a9f6c2448c.png">
<img width="1227" alt="screen shot 2017-01-22 at 5 08 16 pm" src="https://cloud.githubusercontent.com/assets/17788969/22186538/6ef2d134-e0c5-11e6-9dcb-6a04c55b432a.png">

**Comment by alxndrkalinin** [comment]
No time right now to figure out what exactly is wrong. I suspect it has to do with the new version of ui-router. For now fixed by freezing versions of dependencies within SOCR/SOCRAT@ 0b9e7bf7a51f0f1f7a17469557d337cacfd6c142

**Comment by alxndrkalinin** [comment]
@acell you can test if it works now by cloning repo, switching to `dev` branch, and installing dependencies again. To be able to use Iris data locally see instructions in [Contributions file](https://github.com/SOCR/SOCRAT/blob/dev/CONTRIBUTE.md#socr-datasets-for-testing)

**Comment by acell** [comment]
Good looks!

<img width="1184" alt="screen shot 2017-02-02 at 11 38 46 am" src="https://cloud.githubusercontent.com/assets/17788969/22558583/30b4d24e-e93c-11e6-824e-2d32727dce91.png">
