### ISSUE TITLE
alpha slider 

### ISSUE THREAD

**Issue by leedahee** [SOCR/SOCRAT-issues#207]
Could you look at my code and solve this problem?
I just discussed this issue with Brady. He recommended me to ask you to look at this and see if you can deal with it. 

'alpha' in sidebar slider is not working well.
1. value getting from slider is not showing in a box above. 
2. typing alpha or changing value using up/down arrows is not working. 

Thanks!

**Comment by alxndrkalinin** [comment]
@leedahee where is the code exactly?

Please attach the screenshots of debugger stopped on the breakpoints at the places where alpha value is synchronized with the slider and the other way around.

**Comment by leedahee** [comment]
I attached the screenshot. This is presented when I click alpha slider or box. 
https://docs.google.com/document/d/1TMMbsyH4282JyThZpUTXqvCZsvnVkDnFOK1bMfMX1A4/edit
