### ISSUE TITLE
PowerCalc: TwoTest and OneTest debugging

### ISSUE THREAD

**Issue by bradyzhu1102** [SOCR/SOCRAT-issues#230]
Bugs:
- When moving power slider, the whole calculator crashes.

...continue to update

**Comment by alxndrkalinin** [comment]
please don't keep tasks in the `new issues`, instead move it to `In progress` or `backlog` (or `icebox` if you're not going to work on it this sprint)

**Comment by bradyzhu1102** [comment]
OneTest and twoTest problem resolved. Have oneProp and twoProp to solve.

**Comment by bradyzhu1102** [comment]
OneProp and twoProp resolved. (division by 0 error)
