### ISSUE TITLE
SVM Module: Non-numeric Categorical Columns

### ISSUE THREAD

**Issue by andongluis** [SOCR/SOCRAT-issues#287]
- Sidebar: Make mapping and send it to Main Controller:
- Main: Send data to Algorithms and to Graphing
- Graph: Make legend and mapping correctly
- Algorithms: Research necessary format for the classes

**Comment by alxndrkalinin** [comment]
Think about maximum number of classes. Possibly, test on different datasets to find a reasonable limit.
