### ISSUE TITLE
test Data Wrangler

### ISSUE THREAD

**Issue by alxndrkalinin** [SOCR/SOCRAT-issues#41]
Load Iris data into SOCRAT and test Data Wrangler functionality. Compare to the [original app](http://vis.stanford.edu/wrangler/) and create issues on GitHub on all problems you find (if something is not working in SOCRAT, but working in original app).

Also, clone [the code](https://github.com/SOCR/wrangler) locally and look at it structure. In that repo all my latest changes were done in the final compiled file, while we'll need to actually edit raw source code to get down to issues we want to fix/implement. So you'll need to install [Google Closure Compiler](https://developers.google.com/closure/compiler/) as well.

After that we can discuss issues you found and how to start approaching them.

**Comment by alxndrkalinin** [comment]
@raytburg did you make a list of issues as a result of this testing?

**Comment by raytburg** [comment]
@alxndrkalinin I have them written down - forgot to make the issues on Github. I'm currently not at home right now but when I get back can I make one issue containing all the differences I located?

**Comment by alxndrkalinin** [comment]
@raytburg  yes, that sounds good. create a checklist:

- [ ] issue1
- [ ] issue2
etc
