### ISSUE TITLE
learn how to use Bootstrap

### ISSUE THREAD

**Issue by alxndrkalinin** [SOCR/SOCRAT-issues#56]
Go through [W3Schools Bootstrap tutorial](http://www.w3schools.com/bootstrap/).

After that you should be able to recognize Bootstrap-specific classes in HTML, understand how grid works, how to create buttons, inputs, forms, etc.

**Comment by wenyiw** [comment]
I’ve been assigned this before. It’s in review section.

Wenyi Wu
wenyiwu@umich.edu

**Comment by alxndrkalinin** [comment]
@wenyiw sorry, it was supposed to be for another person
