### ISSUE TITLE
Bar Graph, Scatter Plot, Bubble Chart - Data Plotted Outside of Bounds

### ISSUE THREAD

**Issue by acell** [SOCR/SOCRAT-issues#65]
The data (bubbles / dots) are not contained within where they should be (not touching / overlapping / going past any axes). This should probably mean recalculating axes to have slightly more room, and/or elongating them? The bar graph and scatter plot just seem to have data that creep just above or to the right of the axes, which is awkward-looking.

<img width="780" alt="screen shot 2017-02-02 at 11 14 50 am" src="https://cloud.githubusercontent.com/assets/17788969/22557767/881c8782-e939-11e6-9ed4-714e32e82b8b.png">
<img width="775" alt="screen shot 2017-02-02 at 11 15 33 am" src="https://cloud.githubusercontent.com/assets/17788969/22557768/8829a17e-e939-11e6-8b21-98ccea1c03dd.png">

**Comment by acell** [comment]
Dealing with not only adjusting the axes but also making sure that the data is still being plotted accurately while extending the axes in each direction requires / might require enough logic that I'm going to put this off / work on the more simply styling-related pie + ring chart labeling for now--especially because  most work in the next couple months will be in transitioning to vega-lite, and this predicament will probably be very much affected by that transition.

**Comment by alxndrkalinin** [comment]
@acell that's okay, assign `priority:low` and move to the Icebox
