### ISSUE TITLE
start debugging `Get JSON by URL` component

### ISSUE THREAD

**Issue by alxndrkalinin** [SOCR/SOCRAT-issues#87]
Look at [`getJsonByUrl`](https://github.com/SOCR/SOCRAT/blob/master/app/scripts/analysis/GetData/GetDataMainCtrl.controller.coffee#L208) function inside of `GetData` module of SOCRAT. Try setting up a breakpoint and figuring out when and why [JSON parsing](https://github.com/SOCR/SOCRAT/blob/master/app/scripts/analysis/GetData/GetDataJsonParser.service.coffee) fails (and whether it's even called). Function that checks if particular JSON is mappable onto 2D table is [described in GetDataDataAdaptor](https://github.com/SOCR/SOCRAT/blob/master/app/scripts/analysis/GetData/GetDataDataAdaptor.service.coffee#L55).

**Comment by alxndrkalinin** [comment]
@wenyiw okay, for this task let's assume that function `jsonToFlatTable` works as expected. it takes data and returns 2D data array if it's possible and false otherwise. Assuming that error doesn't happen there we still need to figure out why JSON files are not processes. You can do locate the place of the error by starting to debug the [AJAX callback](https://github.com/SOCR/SOCRAT/blob/master/app/scripts/analysis/GetData/GetDataMainCtrl.controller.coffee#L212). Step through the code from there to detect where it fails.

**Comment by alxndrkalinin** [comment]
@wenyiw not sure what was the question about file URL - in general you could use any JSON file found on internet for testing. If you wanted to specifically check mapping onto 2D, I uploaded 2 files for you: [mappable](http://socr-dev.nursing.umich.edu:3000/datasets/test/mappable.json) and [not-mappable](http://socr-dev.nursing.umich.edu:3000/datasets/test/not-mappable.json)

**Comment by chartotu19** [comment]
@alxndrkalinin there is not much clarity on which json formats are we planning to support. Also, The user will need to specify the json structure for us to be able to parse it out reliably everytime. For example,
```
{
    "name" :"car manufacturers",
    "date" : "2016-10-18",
    "data" : [
            {"name":"ford",type:"sedan,truck,suv","market cap":1000,"location":"usa"},
            {"name":"tata",type:"sedan,compact,suv","market cap":200,"location":"india"},
            {"name":"nissan",type:"sedan,truck,suv","market cap":500,"location":"japan"},
            {},
    ]
}
```
User needs to pass `url` and `path="result.data"` and we can parse it out.  I think we should only parse array of nested objects. 

Thoughts?

**Comment by chartotu19** [comment]
popular json datasets for reference - https://github.com/jdorfman/awesome-json-datasets

**Comment by alxndrkalinin** [comment]
@chartotu19 yes, there is no proper description, but idea is simple: try to parse json file and see if it's structure is shallow and consistent to be able to represent if as [2D tabular data](http://socr-dev.nursing.umich.edu:3000/datasets/test/mappable.json) or [not](http://socr-dev.nursing.umich.edu:3000/datasets/test/not-mappable.json). Good idea with relative path – we should incorporate this in further development.

For upcoming submission I see this issue to have overall low priority. I'd suggest we focus on [features](https://github.com/SOCR/SOCRAT-issues#boards?labels=priority%3A%20high&epics=79748116_151&repos=79748116) that are better showcase for uniqueness of SOCRAT compared to what is already available.

**Comment by chartotu19** [comment]
cool, lets revisit this after the submission
